-- MySQL Script generated by MySQL Workbench
-- 04/05/16 04:53:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mergano
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mergano
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mergano` DEFAULT CHARACTER SET utf8 ;
USE `mergano` ;

-- -----------------------------------------------------
-- Table `mergano`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mergano`.`product` (
  `product_id` VARCHAR(13) NOT NULL,
  `category` VARCHAR(30) NOT NULL,
  `type` VARCHAR(30) NULL DEFAULT NULL,
  `manufacture` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `model` VARCHAR(75) NULL,
  `description` VARCHAR(80) NULL DEFAULT NULL,
  `price` VARCHAR(8) NULL DEFAULT NULL,
  `location` VARCHAR(45) NULL,
  `expired` DATETIME NULL,
  `warranty` VARCHAR(3) NULL DEFAULT NULL,
  `quantity` VARCHAR(8) NULL DEFAULT NULL,
  `import_date` DATE NULL DEFAULT '0000-00-00',
  `status` VARCHAR(10) NULL,
  `user_lastmodified` VARCHAR(45) NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mergano`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mergano`.`user` (
  `iduser` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `empno` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `create_time` DATETIME NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mergano`.`backlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mergano`.`backlog` (
  `idbacklog` INT NOT NULL AUTO_INCREMENT,
  `action_type` VARCHAR(45) NULL,
  `action_detail` VARCHAR(45) NULL,
  `date` DATE NULL DEFAULT DD-MM-YYYY,
  `time` TIME(6) NULL,
  `user` VARCHAR(20) NULL,
  PRIMARY KEY (`idbacklog`),
  INDEX `user_idx` (`user` ASC),
  CONSTRAINT `user`
    FOREIGN KEY (`user`)
    REFERENCES `mergano`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mergano`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mergano`.`customer` (
  `idcustomer` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `company` VARCHAR(45) NULL,
  `contact` VARCHAR(45) NULL,
  `date_created` DATETIME NULL,
  PRIMARY KEY (`idcustomer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mergano`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mergano`.`order` (
  `idorder` INT NOT NULL,
  `customer_id` INT NULL,
  `product_id` VARCHAR(45) NULL,
  `quantity` INT NULL,
  `order_status` VARCHAR(45) NULL,
  `user_created` VARCHAR(45) NULL,
  `date_created` DATETIME NULL,
  PRIMARY KEY (`idorder`),
  INDEX `product_id_idx` (`product_id` ASC),
  INDEX `customer_id_idx` (`customer_id` ASC),
  INDEX `user_created_idx` (`user_created` ASC),
  CONSTRAINT `product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `mergano`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mergano`.`customer` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_created`
    FOREIGN KEY (`user_created`)
    REFERENCES `mergano`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mergano`.`request_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mergano`.`request_order` (
  `idrequest` INT NOT NULL,
  `order_id` INT NOT NULL,
  `product_id` VARCHAR(45) NOT NULL,
  `quantity` VARCHAR(45) NULL,
  `stock_location` VARCHAR(45) NULL,
  `user_created` VARCHAR(45) NULL,
  `request_status` VARCHAR(45) NULL DEFAULT 'Pending',
  PRIMARY KEY (`idrequest`, `order_id`),
  INDEX `order_id_idx` (`order_id` ASC),
  CONSTRAINT `order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `mergano`.`order` (`idorder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mergano`.`report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mergano`.`report` (
  `idreport` INT NOT NULL,
  `order_id` INT NULL,
  `customer_id` INT NULL,
  `date` DATE NULL,
  `total` DECIMAL(2) NULL,
  PRIMARY KEY (`idreport`),
  INDEX `customer_id_idx` (`customer_id` ASC),
  INDEX `order_id_idx` (`order_id` ASC),
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mergano`.`customer` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `mergano`.`order` (`idorder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mergano`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mergano`.`invoice` (
  `idinvoice` INT NOT NULL,
  `order_id` INT NULL,
  `customer_id` INT NULL,
  `customer_name` VARCHAR(45) NULL,
  `customer_company` VARCHAR(45) NULL,
  `total_price` DECIMAL(2) NULL,
  `dated_created` DATETIME NULL,
  PRIMARY KEY (`idinvoice`),
  INDEX `order_id_idx` (`order_id` ASC),
  CONSTRAINT `order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `mergano`.`order` (`idorder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mergano`.`notification_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mergano`.`notification_report` (
  `idnotice` INT NOT NULL,
  `report_type` VARCHAR(45) NULL,
  `report_detail` VARCHAR(45) NULL,
  `product_id` VARCHAR(45) NULL,
  `report_status` VARCHAR(45) NULL,
  `user_created` VARCHAR(45) NULL,
  `date_created` DATETIME NULL,
  PRIMARY KEY (`idnotice`),
  INDEX `user_created_idx` (`user_created` ASC),
  CONSTRAINT `user_created`
    FOREIGN KEY (`user_created`)
    REFERENCES `mergano`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
